AWSRegion: "ca-central-1"
CognitoClientID: ""
DBHost: 192.168.86.137
DBName: ""
DBPassword: ""
DBUser: ""
DocAuthor: "Universal Windows"
HSTNumber: ""
LogoURI: "https://ca-universalwindows.s3.ca-central-1.amazonaws.com/public/UniversalLogo.jpg"
S3Bucket: "ca-universalwindows"
SsmPath: "univsales-quote-pdf"
Stage: "prod"